[machine]
entrypoint = "/usr/local/bin/python3 /opt/cartesi/app/app.py"
ram_length = "64Mi"
workdir = "/opt/cartesi/app"

[drives.root]
builder = "docker"
dockerfile = "alpine.dockerfile"
format = "ext2"
extra_size = "16Mb"
